spring.datasource.url=jdbc:postgresql://localhost:5432/subtrack
spring.datasource.username=postgres
spring.datasource.password=lainiwakura
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true